Week 6-7 progress update: Mudit Gupta
TEAMMATES/gsoc-2018 pull request #19
Opened 2018-07-07 11:13 UTC by mg14777

@wenmogu @craaaa Ready for review.

2018-07-31 18:16 UTC, mg14777 commented
This still needs to be merged

2018-08-02 06:30 UTC, wkurniawan07 requested changes
You should not change the plan. If the week's work does not align with the plan, use the retrospect to reflect on/explain why.

2018-08-02 06:30 UTC, wkurniawan07 commented on Mudit_Gupta/progress.md
> +- [x] Finish work on [Student: Feedback submission: Rank question: Improve explanation regarding ranking constraints](https://github.com/TEAMMATES/teammates/pull/8870)
Do not change the plan.

2018-08-02 06:30 UTC, wkurniawan07 commented on Mudit_Gupta/progress.md
> +- [x] Implement drag and drop feature for other question types
Do not change the plan.

2018-08-02 20:31 UTC, mg14777 commented
@wkurniawan07 I have kept the original plan and added explanations.

2018-08-10 04:42 UTC, mg14777 commented
@wkurniawan07 can we merge this ?

2018-08-13 00:09 UTC, mg14777 commented
@wkurniawan07 @xpdavid @wenmogu Please merge this

2018-08-13 06:54 UTC, wkurniawan07 approved these changes

2018-08-13 06:54 UTC, merged