Project Plan Update: Tan Heng Yeow
TEAMMATES/gsoc-2018 pull request #8
Opened 2018-05-29 03:20 UTC by tanhengyeow

Hi @wkurniawan07 @tran-tien-dat 

I updated my project plan based on the discussion made in the past 2 weeks along with my progress update. Please review 😄

2018-05-29 07:36 UTC, wkurniawan07 requested changes

2018-05-29 07:36 UTC, wkurniawan07 commented on Tan_Heng_Yeow/progress.md
> +- Understanding what have been implemented so far
Retrospect is not a list of what you have done. It is more of a reflection on what you have done well, what could be improved, what are the difficulties faced, etc.

2018-05-29 07:36 UTC, wkurniawan07 commented on Tan_Heng_Yeow/progress.md
> +- [ ] Fix issues after code review
You don't really need this kind of entry.

2018-05-30 12:20 UTC, wkurniawan07 approved these changes
LGTM, @tran-tien-dat can merge if you're good with this

2018-05-30 12:48 UTC, tran-tien-dat approved these changes
LGTM

2018-05-30 12:49 UTC, merged